
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install modules
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Static Analysis
        run: npm run ts

      - name: Test
        run: npm run test

      - name: Deploy
        run: npm run deploy

      # TODO:
      # - name: Audit
      #   run: npm run audit
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths